### PR TITLE
draft v0.15.x

### PR DESCRIPTION
**Pull request by tzemanovic**
WARNING: ☠️ do not merge this branch into your development branches and do not rely on it being stable. ☠️

contains:

- #714
- #796
- #856
- #893
- #976
- #1051 - evil [917fbd8](https://github.com/anoma/namada/pull/1269/commits/917fbd8978fd975eab6fb7901cd24317ddc37c3b)
- #1017 - evil [685c757](https://github.com/anoma/namada/pull/1269/commits/685c75795d144ffad4fcb305f76c3303e27d4df0) and [a2545a1](https://github.com/anoma/namada/pull/1269/commits/a2545a1e7e1a1c0045f76cc8914963e48f9b5977)
- #1031
- #1056 
- #1081 - evil [5814cdc](https://github.com/anoma/namada/pull/1269/commits/5814cdc451e5f6b40205147a29f0ded55d6abcf6)
- #1258
- #1106 - evil [239d8ca](https://github.com/anoma/namada/pull/1269/commits/239d8cabd19e83244462dd43516cece12b80c0d5)
- #1116
- #1123 - evil [eb945ae](https://github.com/anoma/namada/pull/1269/commits/eb945ae6d736ebf704f02e645d1c5016b23a5c34) and [b4c4cfa](https://github.com/anoma/namada/pull/1269/commits/b4c4cfa3186c0ee00d65cb5d3ed272d3f925c2ee)
- #1124 - evil [e92fc6e](https://github.com/anoma/namada/pull/1269/commits/e92fc6e9bb63ac43cd1027884ef181418fa735ff)
- #1163 
- #1184
- #1187 
- #1189
- #1256
- #1212
- #1239 
- #1246 
- #1263

### CODE REVIEW

**Comment by Fraccaman** [comment]
pls spawn devnet [anoma-devnet-max4,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
pls spawn devnet [devnet-0.15,3,heliaxdev@1be9883,ON]

**Comment by bengtlofgren** [comment]
pls spawn devnet [devnet-0.15,3,heliaxdev@1be9883,ON]

**Comment by Fraccaman** [comment]
@tzemanovic It could be because we need #1258

**Pull request closed without merging**
